### ISSUE TITLE
Django Interface - SignOn

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#10]
Can the Django Interface also be compatible with Single Sign on?

Users are getting difficulty when they try to logon: 
![image](https://user-images.githubusercontent.com/45364510/138438198-e94d8d89-8873-48dc-89a3-b6bf83e683e7.png)

**Comment by magraeber** [comment]
Does not work out of the box.
But might be possible with some workaround:
https://django-allauth.readthedocs.io/en/latest/advanced.html#admin

**Comment by magraeber** [comment]
We won't implement it.
Instead we will add more admin features to the normal app.
That means you don't need to use two web sites anymore.
