### ISSUE TITLE
Cannot make users an admin in Django

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#11]
When selecting a user to make them an admin: 
![image](https://user-images.githubusercontent.com/45364510/139017474-e90509e3-49f0-42ff-a56e-a750a8aabcd4.png)

After saving it however reverts back to previous: 
![image](https://user-images.githubusercontent.com/45364510/139017710-ce1ca1c5-d859-4409-a945-694d27395ac4.png)

We need to make Mathias Schmid and Alexander Busch admins.

**Comment by PascalPadberg** [comment]
They are admins now. Not sure why you weren't able to do make them admins. We'll check

**Comment by magraeber** [comment]
I have checked it. This read only behavior is on purpose.
Admin rights should only be given from superusers (TLK). Otherwise this leads to security issues.
https://realpython.com/manage-users-in-django-admin/#prevent-non-superusers-from-editing-their-own-permissions

**Comment by Walshest** [comment]
Hi @magraeber, 
We need to add another user as an admin: 
paul.rohmund@danfoss.com
Can you let me know when this is complete please?

**Comment by Walshest** [comment]
Hi @PascalPadberg , 
Can we add admin rights for andrea.sangalli@danfoss.com please? so that he can upload and change models? 

We still need a solution here of a model creator account which isn't an admin: https://github.com/tlkenergy/sim-tlk/issues/9
