### ISSUE TITLE
Make a simulation result as an example that all users can see

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#17]
Hi, 
Is there a way of making a simulation results as an example. 
Therefore users can see this simulation result as a default. 

This is implemented with TLK .FMUs but how do we do it in Django? 

![image](https://user-images.githubusercontent.com/45364510/145561039-dffe249d-80eb-4cf6-9214-7608e86cc2b2.png)

**Comment by PascalPadberg** [comment]
Has been enabled for Admins. Is that okay for now or do you prefer another way to set as an example?

**Comment by Walshest** [comment]
Perfect thanks, 
Feature works now from Django. If you are merging all admin features over to sim.tlk than it would make sense to merge this over too. But works for now :)
