### ISSUE TITLE
.FMU Inputs to models - Constant or Time-varying

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#21]
Hi @PascalPadberg, 

**How are we able to deal with .FMU inputs to a model?** 
- We have a model with 5 inputs that we would either like to change the start value and ideally like to input a time varying profile (by .csv or similar)
- Currently I do not see the inputs defined in the backend?. There is only, variables, parameters and outputs that can be selected
- I remember last year you mentioned a .CSV interface; however you didn't include this in the documentation for Danfoss.

**Comment by PascalPadberg** [comment]
Hi Stefan,
yes we have done some work on a .csv interface for Inputs, we will have a look what we can do in the short term to make it available for you. I'll give you some feedback by end of this week.

**Comment by Walshest** [comment]
> 

That would be great. Even some Django code would be a good start, if the GUI isn't built yet

**Comment by PascalPadberg** [comment]
We need some updates in our backend code to make it work. However, we have to finish integration of folders and improvement of variable handling (Issue #7) first. With that, input handling is only a small step.

**Comment by PascalPadberg** [comment]
Closed with v2.0.0
