### ISSUE TITLE
Bug with adding Booleans as parameters: Start valve shown twice

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#22]
Hi @PascalPadberg , 

There is a bug trying to use booleans as parameters. Start value is shown twice. I was not able to save the .FMU
![image](https://user-images.githubusercontent.com/45364510/160839438-9f1dfd11-a53c-4ef1-bb03-717ec8f7495c.png)

**Comment by PascalPadberg** [comment]
Thanks for reporting it. I'm fixing it right away!

**Comment by PascalPadberg** [comment]
With this bugfix, various other changes will be deployed as well. Originally, we wanted to wait for another 2 weeks, test more and add even more features, but this bug changed plans a little.

**Comment by Walshest** [comment]
Hi @PascalPadberg, 
Can you release it (and fix this bug) when everything is stable and tested please?. We don't want to risk our instance of Sim.TLK crashing. 

Thanks

**Comment by PascalPadberg** [comment]
Yes, we'll do that
