### ISSUE TITLE
Issues with Lineplots

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#23]
Hi @PascalPadberg , 

We have setup a line plot which plots two variables against each other: 
x= dP across a valve
y= Valve Opening Degree

When it plot we get the following error: 
![image](https://user-images.githubusercontent.com/45364510/171015855-7da7efee-af6b-489b-bad1-5fd8f2488a07.png)
We are not able to zoom on the plot. 

You can see this on the .FMU example: DN100_Design4201_ICLX

Note: we are not plotting against time in this example & it works with the scatter plot.

**Comment by PascalPadberg** [comment]
Hi Stefan,
thanks for reporting the issue. The line plot might be a bit misleading as in your case it should be a scatter plot without the markers but a line connecting the data. I tested it already. We will add that as an option!
