### ISSUE TITLE
Search bar for variables / outputs plotting

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#25]
Since version 2.0; there is no way to filter/ search the outputs which I want to plot. 

It is now extraordinarily difficult to be able to find a specific variable. E.g. _Evaporator:summary:path_b:Tliq_
<img width="287" alt="image" src="https://user-images.githubusercontent.com/45364510/189096616-f097532d-111e-4d0b-817a-0af4fcf84d4a.png">
The old method was actually easier as there was a search/filter bar

**Comment by PascalPadberg** [comment]
A filter will be available the next days

**Comment by PascalPadberg** [comment]
Resolved with v2.1.0. Performance for large lists will be improved further
