### ISSUE TITLE
Model Inputs: Graph Issues

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#27]
Hi @PascalPadberg , 

I have noticed that there are some issues with the model input plots: 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/45364510/190093804-56362f1f-c0be-4a00-80ce-5c8b6f7e8d04.png">
Half of the top plot is not showing. This has been noticed in both MS Edge and Google Chrome. 

Tested on model: SimpleACCycle_R134A

**Comment by mateokurti** [comment]
This is now fixed. There is still a smaller issue with the height on some browser, and we're working to have it fixed soon.

**Comment by mateokurti** [comment]
UPDATE: All issues regarding this should be now resolved.
