### ISSUE TITLE
Backend: Plot Settings

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#28]
Hi @PascalPadberg , 

I have noticed that there is a change in the series since the last update: 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/45364510/190095105-e0780d98-0a16-437f-abac-b6f7193890ae.png">
The 2nd series label is not on a new line. 

Additionally **defaults for the timeseries** could be used to save time in plot setup: 
1. Default "Title of x axis": Time
2. Default "Series name:" Name of the variable
3. Default "Title of y-Axis": Name of the variable 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/45364510/190095598-2c7ec6b2-afa6-46dd-9a3a-c86be4872b4e.png">

**Comment by PascalPadberg** [comment]
We'll fix the series order, soon.

Regarding the second request: Good point. That's on the list for quite some time now. Time to implement it...
