### ISSUE TITLE
Discritised Cells for Array plotted correctly? 

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#31]
Hi, 
I have been running a model of an evaporator and looking at the HTC in each cell. I think there may be an issue in how the cells are ordered and plotted. Can you check the array please? 
**Dymola: @ outlet quality 0.95**
![image](https://user-images.githubusercontent.com/45364510/208064706-3e64f96f-9247-4ac4-9e1d-076b35caa44e.png)

**Sim.TLK: @ outlet quality 0.95**
<img width="646" alt="image" src="https://user-images.githubusercontent.com/45364510/208064656-09a46f5e-7b7c-4d6a-9b1e-71a5da6ffcea.png">

**Django Code order:**
It could be that the array isn't ordered from cell 1->35 correctly
<img width="311" alt="image" src="https://user-images.githubusercontent.com/45364510/208064928-0afa71d6-c837-4556-8361-2a2926cbb092.png">

Additionally is it possible to increase the decimal points on the slider?:
It is difficult to find exactly where quality 0.95 is. It only shows 1 and 0.9
<img width="56" alt="image" src="https://user-images.githubusercontent.com/45364510/208065697-0dc1d9e2-e626-453a-b74d-c80365034c9b.png">

**Comment by Walshest** [comment]
> 

I confirmed my theory. There is a bug. 
- The order in Django needs to be changed. 
- I have manually updated it for my usecase

**Comment by PascalPadberg** [comment]
Thanks, we'll fix that bug
