### ISSUE TITLE
Add new user in Django (before they login)

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#32]
Hi, 
A great feature would be to be able to add a list of users to Django before they have been logged into the frontend. 
- https://backend-dan.tlk-energy.de/admin/account/emailuser/ 
Therefore you can assign them to a group and simulation models. 

The current process for new users is: 
1. As them to log into Sim.TLK
2. wait for them to have logged in
3. Admin can then assign them to a group 
4. Then the user can see the simulation models. 

If it is quick to implement it would be best to add their email addresses directly.

**Comment by magraeber** [comment]
I understand the idea. But the whole user registration and authentification stuff is handled by an third party package (django-rest-auth). This kind of workflow is not available there. And customizing it too deeply always means a security risk.

**Comment by magraeber** [comment]
see comment above
