### ISSUE TITLE
Boolean Parameters not working

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#34]
It is not possible to use a Boolean parameter: 
<img width="338" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/ec7b6dd1-4d9a-4ba5-a133-e7c8944bd494">
When a boolean parameter is pulled into the interface it is not able to "Apply" or to "Save"

**Comment by mateokurti** [comment]
This is now fixed, together with another issue that didn't allow to save the FMU after deleting a parameter.
