### ISSUE TITLE
Add units: Heat Flux

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#35]
Hi, 

Can we add more unit such as Heat Flux [W/m2] and larger values of EUR e.g. kEUR, mEUR 

We are not able to edit ourselves on Django.

**Comment by seschweiler** [comment]
Hi,

I just added all units, you mentioned.
We also added the permissions to add/modify units/quantities to the "...Admins" group.
Everyone in this group should now be able to edit units/quantities on the Django admin page.

**Comment by Walshest** [comment]
> Hi,
> 
> I just added all units, you mentioned. We also added the permissions to add/modify units/quantities to the "...Admins" group. Everyone in this group should now be able to edit units/quantities on the Django admin page.

Thanks, I still haven't been able to implement kEUR as I cannot use the automated conversions: https://github.com/tlkenergy/sim-tlk/issues/41
