### ISSUE TITLE
Renaming Plot group doesn't work

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#38]
In the GUI; it doesn't work to rename a group/ tab of plots: 

<img width="319" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/67a009ef-5e82-41cb-8f2d-e7a47215df5f">

Clicking "Rename" & then "edit" doesn't work: 
<img width="215" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/9732d328-9a5a-4e0f-8b24-94c209b71cb5">

**Comment by mateokurti** [comment]
This is now fixed.
