### ISSUE TITLE
Changing the names of an .FMU model

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#4]
When a .FMU model is loaded up, it is named based on what the .FMU is called. 

It would be great if we can rename it based on an alias so what the end user sees is more user friendly. 

It could be for example added in this menu: 
![image](https://user-images.githubusercontent.com/45364510/138434833-7d32f867-9665-452c-abaf-981bd7921e9b.png)

**Comment by Walshest** [comment]
@PascalPadberg , 
We still would need to have a method of renaming a .FMU model. I also see in the future that we may need to add the models into folders as we get more and more models. This could also be implemented here with the name changing. 

I wanted to add onto this; can we also have a button "Save Changes" or similar when we change the .FMU description. Currently to save the description changes, the user needs to click outside of the box to close it (which isn't intuitive)
![image](https://user-images.githubusercontent.com/45364510/161015976-59f0d096-b883-4641-9ff5-056b14c09a07.png)

**Comment by PascalPadberg** [comment]
We'll add the "Save changes" soon and take the FMU folder issue into consideration

**Comment by seschweiler** [comment]
The feature was already implemented.
