### ISSUE TITLE
Bug: Not possible to deselect pH diagram

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#40]
Deselecting one of the cycles on the Ph diagrams doesn't do anything... 

P.s. Is it possible to select a diagram to plot based on an Integer selection from the simulation? E.g. if int == 5  then show PH Cycle, else not selected
![image](https://github.com/tlkenergy/sim-tlk/assets/45364510/6bbc4257-70bc-41a9-9cfe-0a06c8826cbd)

**Comment by seschweiler** [comment]
The issue should be fixed now.

**Comment by seschweiler** [comment]
The bug has been fixed.
