### ISSUE TITLE
No "DisplayUnits" for bar/ column charts - Custom Operations?

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#41]
It is not possible to select display units fo bar /column plots: 

<img width="457" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/692e9151-00d5-4725-9c85-548d18bc09b8">

Therefore want use custom operations to convert from EUR -> kEUR
However this doesn't work: 
<img width="220" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/c83f69af-12b9-4077-b61f-af3c28602097">

How do you correctly use the custom operations`?

**Comment by seschweiler** [comment]
All outputs automatically have a unit, which is read from the model description.
The "yUnit" defines the display unit, which of course needs to match the quantity of the output.
For example, if we have an output that describes a mass it should have the SI unit kg (this info is stored in the "Model Outputs" field of the FMU and can be seen on the Django Admin page). For this output, the available yUnits should be all mass units such as "g" or "mg". 
"€" does not seem to be supported by Modelica as unit. 

If an output does not have a physical unit (unit: 1), all units are available as yUnit.
The custom operation can be used to set up a custom unit conversion.
The example from your screenshot looks correct to me. 
What exactly does not work?

**Comment by Walshest** [comment]
Yes exactly that is the issue that it doesn't define the unit. 

See error information here: 
<img width="460" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/70431fef-e12a-4f95-bec3-e21b5a917157">

I can forward the full email if you need?

**Comment by seschweiler** [comment]
Ah, I think I know what the problem is.
You need to use Pandas operations: 'a.div(1000)'

**Comment by Walshest** [comment]
Perfect!
That worked, thanks a million :) 
<img width="219" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/23b57632-56c5-45a7-b580-718f7376419f">
