### ISSUE TITLE
Cannot Change Plots when I have a long simulation Result Name

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#51]
When the simulation results name is too long; It is not possible to change the plot configuration. 
Pressing these buttons do not do anything.
<img width="476" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/97b9f038-b7e3-44be-a5bc-abf9046410b0">
Solution: Text behind buttons?

**Comment by mateokurti** [comment]
We've improved the UI and this should no longer be an issue. We've also added the possibility to select a default layout for each result menu. The selected grid layout on the FMU Interface will be selected by default on the simulation results interface.

Feedback is appreciated. :)
