### ISSUE TITLE
Bug - Not able to configure plot when there is only one plot

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#54]
When editing a .FMU plot and I only have one plot in the Submenu; I cannot edit it or add variables: 
<img width="971" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/d164b3d6-f2f9-46ed-8193-f8ae20bb7b81">

If I add a 2nd plot this is now available: 
<img width="969" alt="image" src="https://github.com/tlkenergy/sim-tlk/assets/45364510/e5d76542-33d7-4005-a032-c5c39bba4bd7">

**Comment by mateokurti** [comment]
This is now fixed.
