### ISSUE TITLE
Tool requesting TIL Licenses => Simulations failing

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#56]
Hi, 
Sim.TLK seems to reqesting TIL Media licenses. And therefore models are failing
![image](https://github.com/tlkenergy/sim-tlk/assets/45364510/9674fb29-2d5b-4890-af2f-247806dd6f11)

I have quickly downloaded the .FMU and removed the license dependancy with FMu Configrator and this works now. 

Was this an intended change or a bug that got implemented?

**Comment by mateokurti** [comment]
Hi,

It is a bug in our side indeed. I just updated it and should be fixed in a few moments. I'll keep you posted. Sorry for the inconvenience.

**Comment by mateokurti** [comment]
It should now be resolved. Can you please check it works again as expected?

**Comment by Walshest** [comment]
Yes it works. 
Thanks for the very quick fix :)
