### ISSUE TITLE
Change the bug/issue link

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#6]
The bug link should be changed to: https://github.com/tlkenergy/sim-tlk/issues 

![image](https://user-images.githubusercontent.com/45364510/138435875-0ec4a546-52b3-48a3-b666-1320cb263cde.png)

Therefore users can see what bugs are available /requested without having to create a github account  login. 
- An account still needs to be created to write a bug / issue

**Comment by magraeber** [comment]
Good point. We will change it.

**Comment by Walshest** [comment]
Hi @magraeber , 
We noticed that this still hasn't been changed. 
It would also be beneficial if the link to the Github for reporting bugs was in a more obvious place. 
E.g.: at the bottom of the page instead of having to search for it under Account -> Information 
![image](https://user-images.githubusercontent.com/45364510/145415900-c449719f-6cb2-4414-98e5-d921e120e864.png)

**Comment by PascalPadberg** [comment]
It has been updated. The issue can be closed
