### ISSUE TITLE
FMU 1.0 - Note: No planned support (Ansys OptiSLang)

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#8]
FMU 1.0 is not supported e.g. Ansys OptiSLang. 

It has been tested and doesn't work. There are no plans for backwards compatibility from SIM.TLK. 
- No need for TLK to followup on just as a reference that it has been tested and doesn't work. 

I will contact Ansys regarding FMI 2.0 export from OptiSLang

**Comment by magraeber** [comment]
Yes, we don't plan to support FMI 1.0
