### ISSUE TITLE
Additional Level of "ModelCreator"

### ISSUE THREAD

**Issue by Walshest** [tlkenergy/sim-tlk#9]
For the Django backend it was obvious that we need an additional user level: 
1. User - Can run simulations and show results
2. ModelDeveloper - Can also upload .FMUs, configure plots, add images and maybe assign .FMUs to other teams
3. Admin [only people allowed into Django] - Can assign users to different teams, overview who uses the models, can delete models etc.

**Comment by magraeber** [comment]
@Walshest I have added a new group ModelDeveloper with read/write rights for Images and FMUs.
We can test if that gives the functionality you have in mind.
Who should be the first test user?

**Comment by Walshest** [comment]
@magraeber  Great to here. Can we change [andre.sekunda@danfoss.com] & andrea.sangalli@danfoss.com to these model creator level. 
Will this also be something that the Danfoss Admins can select and change who is part of this ModelDeveloper group?

**Comment by magraeber** [comment]
Done.

No, you can't do that yourself. As with the Admin users, these permissions can only be changed by "Super Admins".
